### ISSUE TITLE
3D Security

### ISSUE THREAD

**Issue by CrackerakiUA** [kareniel/angularjs-stripe-elements#11]
Is the plugin support 3D Security with payment intents?
If yes, do you have any wikis for that somewhere?

**Comment by kareniel** [comment]
This is a simple wrapper around Stripe.js and Elements.

Apparently, Stripe.js should display a modal to handle the 3D secure authentication part.

From https://stripe.com/docs/payments/3d-secure/web:

> Pre-built modal: The Payment Intents API integrates tightly with Stripe.js and Elements to simplify the authentication process. If your Stripe integration uses handleCardPayment, handleCardAction or handleCardSetup, Stripe.js automatically handles the authentication process—displaying a modal dialog where the customer can provide the requisite information.
