### ISSUE TITLE
how to do in angularjs 1.x

### ISSUE THREAD

**Issue by cullsin** [kareniel/angularjs-stripe-elements#12]
Hi,

I am using angularjs 1.x version. Can you please suggest me how do Integrate ?

Raja K

**Comment by kareniel** [comment]
Hi,
This library is meant to be used in Angular.js 1.x.

You can find an example of how to use it here:
https://github.com/kareniel/angularjs-stripe-elements/blob/master/example/index.js

**Comment by kareniel** [comment]
Closing this now. If you have any more questions, feel free to open another issue.
