### ISSUE TITLE
stripe-element-decorator disappears

### ISSUE THREAD

**Issue by scriptsure** [kareniel/angularjs-stripe-elements#2]
@kareniel thanks for the sample really helped out...

Works great but i am having this odd issue embedded it into a md-stepper control. The md-stepper is just a custom tab control to give that angular material feel. When i get to the tab for strip CC i see it works fine then if i go to the next tab, then back, the iframe is gone. I no longer see the CC entry box.

Can you think of a reason why the element would disappear... i do see in my controller that the $ctrl.element is not nulled out or anything...

I know this is a little vague...

**Comment by kareniel** [comment]
Can you provide me with an example? I'll be happy to help but it'll be easier if I can see actual code. :) Something like [plunker ](https://plnkr.co) would do the trick.

**Comment by scriptsure** [comment]
Yeah makes sense to hard to debug. I must be missing something glaring. 

Let me get that together

**Comment by scriptsure** [comment]
@kareniel hey man it been forever but it looks like my issue was on the ON destroy. So as i was moving from tab to tab during our sign up process... as the user left the stripe tab with the CC entry it was destroying the stripe element. So when i would navigate back to the stripe tab it was gone.

Does it cause a memory leak or anything if i never destroy it?

**Comment by kareniel** [comment]
Happy to know you found the problem! 🎉 

> Does it cause a memory leak or anything if i never destroy it?

Yeah, it does. But I don't think it would be **that** noticeable.

I'm gonna close this as it seems this issue has been resolved. 
Feel free to open a new issue if there's anything else! 😄
