### ISSUE TITLE
You must provide a Stripe Element or a valid token type to create a Token.

### ISSUE THREAD

**Issue by nitishkumarnitc** [kareniel/angularjs-stripe-elements#7]
I am trying to tokenize the card whose values collected from the form is.
$scope.card = {
  "address_city": "Bengaluru",
  "address_country": "India",
  "address_line1": "14th main",
  "address_state": "Karnataka",
  "address_zip": "123456",
  "cvc": "123",
  "expMonth": "12",
  "expYear": "2019",
  "name": "Nitish Kumar",
  "number": "42424242424242424242"
}

Function used is - 
StripeElements.createToken($scope.card, function (response) {
})

 Error - You must provide a Stripe Element or a valid token type to create a Token.
    at new t ((index):1)
    at (index):1
    at e.<anonymous> ((index):1)
    at e.createToken ((index):1)

**Comment by kareniel** [comment]
Have you followed the example in the [readme](https://github.com/kareniel/angularjs-stripe-elements/blob/master/README.md)? If so, how is your use case different from the example?

**Comment by nitishkumarnitc** [comment]
Thanks @kareniel. It was working fine when I was using https://github.com/bendrucker/angular-stripe , it is based on stripe version 2. May be things have changed in version 3.

**Comment by kareniel** [comment]
@nitishkumarnitc Yes, you're right. This library is based on version 3, which works differently than v2.
Try adapting your code using the information in the readme and let me know if you're still having trouble after that, I'll do my best to help :)

**Comment by nitishkumarnitc** [comment]
Thanks @kareniel . I changed my code according to version 3 and it worked fine.

**Comment by kareniel** [comment]
Cool! :) 

Closing.
