### ISSUE TITLE
How to change stripe publishable key dynamically?

### ISSUE THREAD

**Issue by nitishkumarnitc** [kareniel/angularjs-stripe-elements#8]
I want to change stripe key dynamically. 
Right now its getting configured in config. 
I want to change it using StripeElements which is injected in controllers. 
angular.config(function (StripeElementsProvider) {
  StripeElementsProvider.setAPIKey(STRIPE_API_PUBLISHABLE_KEY)
})

How can I do that ?

**Comment by kareniel** [comment]
You'd have to create a new instance of the the Stripe object.

You can't do that with the way this library works, because the key is passed to the Stripe constructor during application bootstrap, and the created instance is used from then on.

**Comment by kareniel** [comment]
Closing for now. Feel free to open a new issue if you have more questions!
